default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: snack_rails_deployment_development

test:
  <<: *default
  database: snack_rails_deployment_test

production:
  <<: *default
  database: snack_rails_deployment_production
  username: <%= ENV['DEPLOYER_USERNAME'] %>
  password: <%= ENV['DEPLOYER_PASSWORD'] %>
